---
title: "10x Genomics Xenium Mouse Brain"
author: "Lauren Rusnak"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prep

```{r}
library(MoleculeExperiment)
library(SpatialExperiment)
library(STexampleData)
library(scran)
library(ggplot2)
library(ggspavis)
library(scater)
library(smoothclust)
library(stats)
library(mclust)
library(randnet)
library(R.utils)
library(tibble)
```



## Import Data


```{r}
# Create molecule experiment object
setwd("C:/Users/lerus/OneDrive/Documents/BU-AB/ResearchRotation")
baseDir <- getwd()
dataDir <- file.path(baseDir,"10xXeniumData")

me <- readXenium(dataDir, keepCols = "essential") # takes about 3 minutes
me
```

```{r}
# transform into spatial experiment object
spe <- countMolecules(me)
spe
```
- takes ~10-15 minuts


### Normalization

```{r}
spe <- logNormCounts(spe) 
spe
```


### **Run smoothclust with different parameters**

#### Method: Uniform

```{r}
# library(smoothclust)
spe <- smoothclust(spe, method = "uniform")
assayNames(spe)
```
  - takes about 35 minutes
  


##### Dimensionality reduction

```{r}
# Principal Component Analysis
set.seed(123)
spe <- runPCA(spe, ncomponents = 50, exprs_values = "logcounts_smooth")

dim(reducedDim(spe, "PCA"))

# Vector of principal commponents for clustering 
pcs <- reducedDim(spe, "PCA")
```

```{r}
# UMAP
set.seed(123)

spe <-  runUMAP(spe, dimred= "PCA", exprs_values = "logcounts_smooth")

dim(reducedDim(spe, "UMAP"))

colnames(reducedDim(spe, "UMAP")) <- paste0("UMAP", 1:2)

```



##### K-means clustering 

###### Deciding Number of clusters


```{r}
n_clusters <- 15

# Initialize total within sum of squares error: wss
wss <- numeric(n_clusters)

set.seed(123)

# Look over 1 to n possible clusters
for (i in 1:n_clusters) {
  # Fit the model: km.out
  km.out <- kmeans(pcs, centers = i, nstart = 20)
  # Save the within cluster sum of squares
  wss[i] <- km.out$tot.withinss
}
```


```{r}
# Produce a scree plot
wss_df <- tibble(clusters = 1:n_clusters, wss = wss)
 
scree_plot <- ggplot(wss_df, aes(x = clusters, y = wss, group = 1)) +
    geom_point(size = 4)+
    geom_line() +
    xlab('Number of clusters') +
    scale_x_continuous(breaks = c(2,4,6,8,10,12,14,16))
scree_plot
```



```{r}
## 75centers (one fore each true layer + 1 for white matter)

set.seed(123)

km.5 <- kmeans(pcs, centers = 5)

table(km.5$cluster)

# kmeans cluster assignments
km.clus5 <- km.5$cluster

# store cluster label in column 'label' in colData
colLabels(spe) <- factor(km.clus5)
```

###### **Visualization**


*Reduced Dimensionality Cluster Visualization*
```{r}
# plot clusters in PCA reduced dimensions
plotDimRed(spe, type = "PCA", 
           annotate = "label", palette = "libd_layer_colors",
           size = 0.5)

# plot clusters in UMAP reduced dimensions
plotDimRed(spe, type = "UMAP", 
           annotate = "label", palette = "libd_layer_colors",
           size = 0.5)
```

```{r}
xyplot_uni <- plotSpots(spe, annotate = "label", 
          palette = "libd_layer_colors",
          size = 0.7)
xyplot_uni
```



#### Method: Kernel, bandwidth = 0.5

```{r}
# library(smoothclust)
spe <- smoothclust(spe, method = "kernel", bandwidth = 0.5)
assayNames(spe)
```



